import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../styles/globals.css";
import SideMenu from "./_components/SideMenu";

interface LayoutProps {
  includeSideMenu?: boolean;
}

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  includeSideMenu = true,
}: {
  children: React.ReactNode;
  includeSideMenu?: boolean;
}) {
  return (
    <html lang="en">
      <body className="bg-color-default text-color-default">
        {children}
        {includeSideMenu && <SideMenu />}
      </body>
    </html>
  );
}
